"""Repository-internal immutable semantic descriptors shared by frontends."""

from .bitfield import BitfieldLayout, BitfieldLayoutError
from .bitmask import normalize_patterns, parse_bitmask, parse_bitmask_checked
from .constraints import (
    DEFAULT_FINITE_SET_LIMIT,
    MAX_STATIC_TRANSFER_SHIFT,
    ClosedInterval,
    Constant,
    Constraint,
    ConstraintError,
    ConstraintValue,
    FiniteSet,
    Unknown,
    ValueConstraint,
    constraint_for_type,
    finite,
    finite_values,
    integer_bounds,
    is_exhaustive,
    join,
    meet,
    prove_within,
    transfer_bits,
    transfer_compare,
    transfer_static_binary,
)
from .types import (
    ACType,
    ArrayType,
    BitsType,
    BoolType,
    EnumType,
    StructType,
    TupleType,
    ValueField,
    ValueType,
    ValueTypeError,
)

__all__ = (
    "ACType",
    "ArrayType",
    "BitfieldLayout",
    "BitfieldLayoutError",
    "BitsType",
    "BoolType",
    "ClosedInterval",
    "Constant",
    "Constraint",
    "ConstraintError",
    "ConstraintValue",
    "DEFAULT_FINITE_SET_LIMIT",
    "EnumType",
    "FiniteSet",
    "MAX_STATIC_TRANSFER_SHIFT",
    "StructType",
    "TupleType",
    "Unknown",
    "ValueConstraint",
    "ValueField",
    "ValueType",
    "ValueTypeError",
    "constraint_for_type",
    "finite",
    "finite_values",
    "integer_bounds",
    "is_exhaustive",
    "join",
    "meet",
    "normalize_patterns",
    "parse_bitmask",
    "parse_bitmask_checked",
    "prove_within",
    "transfer_bits",
    "transfer_compare",
    "transfer_static_binary",
)
